# This file was generated by GoReleaser. DO NOT EDIT.
cask "annave-pdf-engine" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "2acc5f681be654a93b343e6b4dafc7a5a140d3cb8927c7c3dfb9d76fa1417674"
      url "https://github.com/annavetech/annave-pdf-engine-golang/releases/download/v#{version}/annave-pdf-engine_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "508b18bcefdc88703d67b5d7b083792c59caf8497ecb57f392ebb6e76943f028"
      url "https://github.com/annavetech/annave-pdf-engine-golang/releases/download/v#{version}/annave-pdf-engine_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "69c349a2628f1819e99001226c898e0bca9d394196be5753fcc902e13e577a50"
      url "https://github.com/annavetech/annave-pdf-engine-golang/releases/download/v#{version}/annave-pdf-engine_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c0e0a993a94e95976e3258f0077f1d89d6d49cb478ffc92042e1ea2a45c3dc2d"
      url "https://github.com/annavetech/annave-pdf-engine-golang/releases/download/v#{version}/annave-pdf-engine_#{version}_linux_arm64.tar.gz"
    end
  end

  name "annave-pdf-engine"
  desc "Convert documents to PDF from the command line — ANNÁVE PDF Engine"
  homepage "https://www.annave.tech"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "annave"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/annave"]
    end
  end

  # No zap stanza required

end
