# This file was generated by GoReleaser. DO NOT EDIT.
cask "annave-pdf-engine" do
  version "1.3.1"

  on_macos do
    on_arm do
      sha256 "98a9cb2347da3ad1f03c74072378760604f1b59428d117416dd5d0abab632ff6"
      url "https://github.com/annavetech/pdfengine/releases/download/v#{version}/annave-pdf-engine_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e0aaf2f4454a044a4e76885d57d16951d70ded820fdd54ad512b16a80a0736dc"
      url "https://github.com/annavetech/pdfengine/releases/download/v#{version}/annave-pdf-engine_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f72dd927b68213d97a0850d57dc253e34cd55bc8667a8c35fd4f1c2c6d87f9eb"
      url "https://github.com/annavetech/pdfengine/releases/download/v#{version}/annave-pdf-engine_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0aefd3f6c924d4e96fc50b61a8cb05b49bc09de808c9b6cd552d2d7c20225a31"
      url "https://github.com/annavetech/pdfengine/releases/download/v#{version}/annave-pdf-engine_#{version}_linux_amd64.tar.gz"
    end
  end

  name "annave-pdf-engine"
  desc "Convert documents to PDF from the command line (ANNÁVE PDF Engine)"
  homepage "https://www.annave.tech"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "annave"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/annave"]
    end
  end

  # No zap stanza required
end
